#!/usr/bin/zsh
#set -e
#with -O3 -march=native and g++ 12 or 13, the result slightly differs (order, rounding). That's suspicious, but ok if the difference is just that.
g++-snapshot ripser.cc -O2 -DNDEBUG -Wall -g `gudhi-includes` `boost-includes` || exit -1
# push
time ./a.out --format point-cloud ~/repos/ripser/examples/o3_1024.txt >! /tmp/new1
# pop
time ./a.out --format point-cloud ~/repos/ripser/examples/o3_4096.txt --threshold 1.6 >! /tmp/new2
# apparent_pair (get_simplex_vertices + dist) - edge_collapse would help
time ./a.out --format point-cloud --dim 2 --threshold .7 tore >! /tmp/new3
# apparent_pair (get_simplex_vertices) - no edge collapse possible
time ./a.out --format point-cloud circle24 --dim 25 >! /tmp/new4

# for i in new*; do mv $i old${i#new}; done
